### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by tessus** [herdsothom/joplin-insert-date#1]
I've checked the code and it seems that you've hardcoded the date format.

I'm pretty sure that people would rather use the format they've specified in the Joplin settings.

**Comment by tessus** [comment]
I can either create a PR or give you a hint on how to do it. Although I'm going back to bed now....

**Comment by herdsothom** [comment]
Hey, thanks for raising that. Yea that was definitely feedback I was expecting.
Happy for you to give me a hint on how to do it, but I'll try to figure it out :)

BTW is there a way to use a joplin import in the plugin?
For example the `useWindowCommandHandler.ts` file in Joplin imports `time` from `'@joplin/lib/time'`
Is it possible for me to use `'@joplin/lib/time'` in my plugin?

New to JS dev as you can probably tell.

**Comment by herdsothom** [comment]
Thanks for your comment @tessus 
I've briefly updated the plugin to use the date format from settings and published it

I'll update it to watch for changes to settings tomorrow so that the application doesn't have to be loaded for a change to the dateFormat to be reflected

**Comment by tessus** [comment]
I already woke up to your update, so you didn't need my hint. ;-)
